### PR TITLE
draft templates

### PR DESCRIPTION
**Pull request by ebullient**
Draft templates for diataxis transition (opened against my own repo for now).

A few other notes (listed here based on Max's comments below):

- The directory structure: `diataxis` vs `asciidoc` is temporary, to identify what has been touched and what hasn't. Consider it an internal detail (not surfaced on the website).
- the `doc-*` pages are intended for those that will be contributing to Quarkus documentation, so they understand the intent/distinction between the four types of docs. This content also provides exemplars of each type: `doc-*-tutorial.adoc` for tutorials, `doc-*-howto.adoc` for how-tos, `doc-*-concept.adoc` for concepts, and `doc-*-reference.adoc` for references.

Content (checked is ready for review)

- Tutorials
  - [x] End result exemplar tutorial: `docs/src/main/diataxis/examples/acme-new-project-tutorial.adoc` (code snippets, commands, results, etc.)
  - [x] Tutorial explaining how to write the above tutorial: `docs/src/main/diataxis/doc-create-tutorial.adoc`
  - [x] Template for creating new tutorials: `docs/src/main/diataxis/_template-tutorial.adoc`
  - [ ] Tutorial for creating a how-to
  - [ ] Tutorial for creating a concept document
  - [ ] Tutorial for creating a reference document
- How-tos
  - [ ] Template for creating new how-tos: `docs/src/main/diataxis/_template-howto.adoc`
  - [ ] How to create content (options/techniques for structuring documents, choosing the right type, including content.. could be one or several, we'll see)
- Concepts
  - [ ] Template for creating new concept documents: `docs/src/main/diataxis/_template-concept.adoc`
  - [ ] Quarkus documentation concepts (explanation of/motivation for Diataxis) 
- Reference
  - [ ] Template for creating new concept documents: `docs/src/main/diataxis/_template-reference.adoc`
  - [ ] Quarkus documentation reference (detailed reference for writing/contributing to quarkus docs)

Yes, this is a lot. But we're trying to address the needs of the four types of users interested in contributing to Quarkus documentation. It is definitely a meta exercise, but we hope to set a good example that can be easily followed by others.

### CODE REVIEW

**Comment by maxandersen** [comment]
just a first feedback, this folder/content is for contributors know how to write docs, right ? 

I would avoid having "diataxis" front-and-center as that makes it looks much more taunting than it have to be. 

How about putting it under `contrib-docs`  and then just in readme notice that the doc layout we use is inspired by diataxis and a link to it ?

**Comment by ebullient** [comment]
> just a first feedback, this folder/content is for contributors know how to write docs, right ?

We will have tutorial/how-to/concept/reference (all the types) for how to write docs. Consider the `diataxis` directory as temporary to distinguish "docs that have been touched to match" and those that haven't. This is an organization reached with @gsmet. We will not be rewriting all of the docs out of the gate, but this will help us track which have been "redone" and which haven't. 

> I would avoid having "diataxis" front-and-center as that makes it looks much more daunting than it have to be.

Diataxis must be front and center so people understand the tone we're trying to maintain for each document. There will be a concept doc that makes it easier to digest, as well as tutorials, how-tos, and a reference that describes conventions, etc. Without the description of the type, it will be too easy to slide back into the mixed muddle we have now (old habits...). The goal is to make the concepts easy to understand, and to have the help handy to explain how to do the things (which also provides exemplars to copy).

> How about putting it under `contrib-docs` and then just in readme notice that the doc layout we use is inspired by diataxis and a link to it ?

We might eventually do that, but the flat structure makes things easy to find/skim when you're looking at source. contrib-docs puts it too far out of the way. 

Don't consider this a barrier. In my experience, engineers actually like having templates/help that explain what they should be writing (given that writing can be hard anyway). It frames the task, and lets them know exactly what they need to do.

**Comment by maxandersen** [comment]
im not arguing against having templates - just that ditaxis has zero meaning for anyone or at least most coming to this content to learn.

**Comment by ebullient** [comment]
> im not arguing against having templates - just that ditaxis has zero meaning for anyone or at least most coming to this content to learn.

The directory name is an internal detail (just as the docs directory is), and it is temporary. The Diataxis framework will be explained in a concept doc specifically intended for contributors.

**Comment by maxandersen** [comment]
> We might eventually do that, but the flat structure makes things easy to find/skim when you're looking at source. contrib-docs puts it too far out of the way.

Just so i'm sure i'm looking at the right things:

includes/devtools - is just a copy from current setup. not relevant/particular to this, right?
thus ask is just to look at the doc-* adoc files ?

One aspect just on top of my mind is how this change affects ja.quarkus.io and upcoming es.quarkus.io/ch.quarkus ?

**Comment by ebullient** [comment]
> Just so i'm sure i'm looking at the right things:
> 
> includes/devtools - is just a copy from current setup. not relevant/particular to this, right? thus ask is just to look at the doc-* adoc files ?

Yes. There may be tweaks/improvements to the includes, which is why I copied them over (so we could feel free to make them). I moved the extension status snippet into the includes dir, e.g., and I have a few other questions that come to mind as I'm trying to work through the different doc types.

> One aspect just on top of my mind is how this change affects ja.quarkus.io and upcoming es.quarkus.io/ch.quarkus ?

There is no avoiding it, this is going to be a huge challenge for the translated sites, because the content/structure of our docs is going to change a lot over time (see James Cobb's design). In the end, it should be easier to translate because the content will be more focused, but the transition will be a lot of work for all of us.

**Comment by maxandersen** [comment]
About translation - that is mainly based on .po files thus the layout is less relevant. if the same sections of text are present. Then the translation will still work.

**Comment by ebullient** [comment]
> About translation - that is mainly based on .po files thus the layout is less relevant. if the same sections of text are present. Then the translation will still work.

Content is going to shift/move around _a lot_ (over time), which is the whole point of this exercise.

**Comment by ebullient** [comment]
Moving to Quarkus issue / merging code so we can play with links + build: 

First pass of code (still preserving diataxis directory to avoid conflicts while we experiment): 
https://github.com/quarkusio/quarkus/pull/25354

**Pull request closed without merging**
